name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Ejecutar tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Instalar dependencias
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Ejecutar tests
        run: php artisan test

  lint:
    name: Revisar formato de código
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Instalar dependencias
        run: yarn install --force

      - name: Ejecutar Prettier y ESLint
        run: |
          npm run lint
          npm run format

      - name: Ejecutar Pint (PHP Linter)
        run: ./vendor/bin/pint

  deploy:
    name: Desplegar en DigitalOcean
    needs: [test, lint]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Conectar al servidor y desplegar
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /var/www/book-reviews
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            yarn install
            yarn run build
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            php artisan route:clear
            php artisan config:cache
            php artisan queue:restart
            sudo systemctl restart php8.3-fpm
            sudo supervisorctl restart inertia-ssr
