name: Build, Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Create Database
        run: touch ./database/database.sqlite

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Install Node.JS Dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.0'

      - name: Install NPM Dependencies
        run: npm install --force

      - name: Build Assets with Vide
        run: npm run build

      - name: Generate Key
        run: php artisan key:generate

      - name: Run Migrations
        run: php artisan migrate

      - name: Execute tests (Unit tests) using Pest
        run: php artisan test --testsuite=Unit
